### ISSUE TITLE
I met an error

### ISSUE THREAD

**Issue by abigsaltyfish** [tinoryj/MetaDedup#1]
hello,when I run "./server [meta port] [data port] [key port]",it throw "error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small:../ssl/ssl_rsa.c:310",Have you ever met such a mistake?

**Comment by tinoryj** [comment]
﻿
﻿That version‘s ssl keys may out of date，you can try to regenerate the keys. the problem should be solved.

发自任彦璟

**Comment by tinoryj** [comment]
﻿That version‘s ssl keys may out of date，you can try to regenerate the keys. the problem should be solved.

**Comment by abigsaltyfish** [comment]
Thank you for your answer
